version: "3.1"
services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=sAAdA23342
      - MYSQL_DATABASE=dockerTraining

  app:
    depends_on:
      - database
    build: ../../../../.
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/dockerTraining